name: mixpanel_analytics
description:
  A dart wrapper on the mixpanel REST API to be used in Flutter applications.
  As this is using the http REST API it works both with Android and iOS.
version: 1.4.0
homepage: https://github.com/Alpha-health/mixpanel_analytics
repository: https://github.com/Alpha-health/mixpanel_analytics
issue_tracker: https://github.com/Alpha-health/mixpanel_analytics/issues

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  shared_preferences: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.0

flutter:
